version: "1.2"

volumes:
  postgres:
  rabbitmq:

services:
  rabbitmq:
    image: rabbitmq:management
    hostname: babushkin_pogreb
    container_name: rabbitmq
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - babushkin_pogreb

  postgres:
    image: postgres:latest
    container_name: bot_postgres
    restart: on-failure
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=pogreb_db
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
    networks:
      - babushkin_pogreb
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  babushkin_pogreb:
    driver: bridge