version: "1.1"

services:
  rabbitmq:
    image: rabbitmq:management
    hostname: babushkin_pogreb
    container_name: rabbitmq
    restart: always
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - babushkin_pogreb

networks:
  babushkin_pogreb:
    driver: bridge