version: "1.0"

services:
  rabbitmq:
    image: rabbitmq:latest
    hostname: babushkin_pogreb
    restart: always
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASSWORD=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq